### ISSUE TITLE
A way to run more functions

### ISSUE THREAD

**Issue by kasvith** [jerverless/jerverless#29]
# Motivation

Currently jerverless supports only one endpoint. `/function`, what if we can make it flexible, to add more function handlers?

# Proposal
We can add
- Function endpoints 🔢  : so people can also build apps using `jerverless` using anything they like. One instance now can handle more functions like `/foo`, `/bar`
- Request Mappers 🤜  : Some functions may need special formatting in requests, with this users can build their own request mappers which maps a traditional http request in to the format they want
- Response Mappers 🤛 : Oh yes, we need the other way also, what if you want a JSON response? a XML ? even an HTML ? what if an user wanted to reshape the response of application without touching the code ? (maybe its legacy, we know nobody touches it if it works 😉), well now they can also define response mappers
- Request Restrictions 🛑  : On some point users may want to force the clients to use a HTTP method like GET, PUT, POST etc, we now allow to restrict them 😉 (or can we add this to mapper? its also okey)

More to come

# Roadmap

- [x] Endpoints
- [x]  Input Mappers
- [x] Response Formatters

**Comment by shalithasuranga** [comment]
Added input mapper initial work in https://github.com/jerverless/jerverless/pull/32

**Comment by shalithasuranga** [comment]
Added output mapper initial work in https://github.com/jerverless/jerverless/pull/37

**Comment by shalithasuranga** [comment]
Added multiple endpoints support in https://github.com/jerverless/jerverless/commit/7f9b8dc1922b4b90b8a66d409ada2e45407216db

**Comment by kasvith** [comment]
LGTM

We can do a release

**Comment by kasvith** [comment]
Endpoints now have been updated using new YAML syntax #43
