### ISSUE TITLE
Deserialize stdin into JSONable interface?

### ISSUE THREAD

**Issue by tirumaraiselvan** [jerverless/jerverless#38]
Since the HTTP data is POSTed, it will be more natural for the function to receive a JSON object rather than an input stream and output a JSON object. This will help in porting the functions to other cloud providers which also receive a JSON event object.

Something like this:

```
const rl = readline.createJSONInterface({
    input: process.stdin
});
```

**Comment by shalithasuranga** [comment]
Thanks for posting an issue :) . jerverless is a little bit different comparing with aws lamda etc. In jerverless function handler(a simple console program) and jerverless component are independent things. Therefore anything can be executed as a serverless function. aws lamda things introduce a library for each language so they can receive json objects or whatever, in other hand jerverless receives raw text payload to the handler by supporting all the languages in the world :)

**Comment by kasvith** [comment]
This can be achieved using a JSON Input mapper,
Feature will be added in future releases

**Comment by tirumaraiselvan** [comment]
Cool. Also, I hope you have also looked at https://github.com/Stackvana/microcule which seems like a similar tool.

**Comment by kasvith** [comment]
Will close the issue as its not related
