### ISSUE TITLE
Error: Could not find or load main class org.jerverless.boot.BootServer

### ISSUE THREAD

**Issue by isurunuwanthilaka** [jerverless/jerverless#44]
I'm just setting up the environment on windows.

Having this issue.

`$ java -jar build/libs/jerverless-1.0.0.jar`
`Error: Could not find or load main class org.jerverless.boot.BootServer`

Check the build.gradle
`jar {
    manifest {
        attributes 'Main-Class': 'org.jerverless.boot.BootServer'
    }
}`

**Comment by kasvith** [comment]
thanks @isurunuwanthilaka

**Comment by isurunuwanthilaka** [comment]
👍

**Comment by kasvith** [comment]
We recommend highly you to run **jerverless** by running `./gradlew installDist`
It will place a `shell` and `bat` script in `build/install/jerverless/bin` directory.
Run it according to your environment, it will set all the `classpaths` out of the box.
