### ISSUE TITLE
Command in cmd work only with right size (Help <> help)

### ISSUE THREAD

**Issue by daxter44** [jerverless/jerverless#52]
Someone can type Help or HELP (with CapsLock) and help will not appear. 
Issue from my experience with software.

**Comment by kasvith** [comment]
Can you do a PR for this :)

**Comment by daxter44** [comment]
Of course, i made command which show you current used Config too. 
Should i made issue for this first or just PR ? 
Or it useless ? :P

**Comment by kasvith** [comment]
no its fine :)

**Comment by kasvith** [comment]
With #53
