### ISSUE TITLE
Can't change configuration during runtime

### ISSUE THREAD

**Issue by isurunuwanthilaka** [jerverless/jerverless#65]
javerless.yml file is loaded on application booting time.To add a function, there is a down time therefore working functions also have to be stopped for sometime, better to add a feature to scan changes in javerless.yml file once in 1 minute (or respectively).

**Comment by shalithasuranga** [comment]
maybe we can introduce these commands to cli 
`config set <key> <value>`
`config remove <key>`
`condig get <key>`

Can we do easily persist changes to `.yml` ?

I think recurrent file read is not good idea. Instead user may use CLI commands or restart jerverless

@kasvith  WDYT?

**Comment by kasvith** [comment]
Scanning per minute is not a good option IMO, usually once deployed its hardly changing the route settings etc by the admins.

But reloading config is a good idea

**Comment by shalithasuranga** [comment]
Yeah we can go with `config reload` like thing I guess. Later we can add to our dashboard UI too
